name: Unittests

on: [push, pull_request]

jobs:
  test:
    name: Run Unittests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install Poetry
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
        export PATH="$HOME/.poetry/bin:$PATH"

    - name: Install Dependencies
      run: poetry install

    - name: Run Unittests
      run: poetry run python -m unittest discover -s tests -v
