fanan:
  PRNGKey: 0
  seed: 37
  total_steps: 1000
  log_interval: 10
  batch_size: 8


mesh:
  n_data_parallel: 1
  n_fsdp_parallel: 1
  n_sequence_parallel: 1
  n_tensors_parallel: 1


data:
  dataset_name: "oxford_flowers102"
  batch_size: 16
  cache: False
  image_size: 64
  num_channels: 3


arch:
  architecture_name: "ddim"


fanan:
  seed: 0
