fanan:
  seed: 37
  log_interval: 10


mesh:
  n_data_parallel: 1
  n_fsdp_parallel: 1
  n_sequence_parallel: 1
  n_tensors_parallel: 1


data:
  dataset_name: "oxford_flowers102"
  batch_size: 512
  cache: False
  image_size: 128
  num_channels: 3


arch:
  architecture_name: "ddim"
  diffusion:
    diffusion_steps: 128


training:
  total_steps: 10_000
  eval_every_steps: 100

