fanan:
  seed: 37
  log_interval: 10


mesh:
  n_data_parallel: 1
  n_fsdp_parallel: 1
  n_sequence_parallel: 1
  n_tensors_parallel: 1


data:
  dataset_name: "oxford_flowers102"
  batch_size: 8
  cache: False
  image_size: 32
  num_channels: 3


arch:
  architecture_name: "ddim"
  image_size: [32, 32]
  feature_stages: [32, 64]
  block_depth: 2
  diffusion:
    diffusion_steps: 128


training:
  total_steps: 10_000
  eval_every_steps: 100


