fanan:
  seed: 37
  log_interval: 10


mesh:
  n_data_parallel: 4
  n_fsdp_parallel: 1
  n_sequence_parallel: 1
  n_tensors_parallel: 1


data:
  dataset_name: "oxford_flowers102"
  image_size: [64, 64]
  num_channels: 3
  batch_size: 64
  cache: False


arch:
  architecture_name: "ddim"
  image_size: [64, 64]
  feature_stages: [32, 64, 96, 128]
  block_depth: 2
  embedding_dim: 32
  embedding_max_frequency: 1000.0
  diffusion:
    diffusion_steps: 80

optimization:
  optimizer_type: "adamw"
  optimizer_kwargs:
    b1: 0.9
    b2: 0.999
    eps: 1.0e-8
    weight_decay: 1.0e-4
  lr_schedule:
    schedule_type: "constant_warmup"
    lr_kwargs:
      value: 1.0e-3
      warmup_steps: 128


training:
  total_steps: 10_000
  eval_every_steps: 1000


